/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnnouncementModal: typeof import('./src/components/Modals/AnnouncementModal.vue')['default']
    Announcements: typeof import('./src/components/Announcements.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AssessmentPlugin: typeof import('./src/components/AssessmentPlugin.vue')['default']
    Assignment: typeof import('./src/components/Assignment.vue')['default']
    AssignmentBlock: typeof import('./src/components/AssignmentBlock.vue')['default']
    AudioBlock: typeof import('./src/components/AudioBlock.vue')['default']
    Autocomplete: typeof import('./src/components/Controls/Autocomplete.vue')['default']
    ChapterModal: typeof import('./src/components/Modals/ChapterModal.vue')['default']
    CourseAssessmentModal: typeof import('./src/components/Modals/CourseAssessmentModal.vue')['default']
    CourseCardOverlay: typeof import('./src/components/CourseCardOverlay.vue')['default']
    CourseCardToDo: typeof import('./src/components/CourseCardToDo.vue')['default']
    CourseOutline: typeof import('./src/components/CourseOutline.vue')['default']
    DesktopLayout: typeof import('./src/components/DesktopLayout.vue')['default']
    DiscussionActivity: typeof import('./src/components/DiscussionActivity.vue')['default']
    DiscussionActivityBlock: typeof import('./src/components/DiscussionActivityBlock.vue')['default']
    DiscussionModal: typeof import('./src/components/Modals/DiscussionModal.vue')['default']
    DiscussionReplies: typeof import('./src/components/DiscussionReplies.vue')['default']
    Discussions: typeof import('./src/components/Discussions.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    Exam: typeof import('./src/components/Exam.vue')['default']
    ExamBlock: typeof import('./src/components/ExamBlock.vue')['default']
    ExamGraded: typeof import('./src/components/ExamGraded.vue')['default']
    ExamQuestionEditor: typeof import('./src/components/ExamQuestionEditor.vue')['default']
    FolderBlock: typeof import('./src/components/FolderBlock.vue')['default']
    FolderPlugin: typeof import('./src/components/FolderPlugin.vue')['default']
    InstructorAvatar: typeof import('./src/components/InstructorAvatar.vue')['default']
    LessonContent: typeof import('./src/components/LessonContent.vue')['default']
    Link: typeof import('./src/components/Controls/Link.vue')['default']
    MissingData: typeof import('./src/components/MissingData.vue')['default']
    MultiSelect: typeof import('./src/components/Controls/MultiSelect.vue')['default']
    OpenQuestion: typeof import('./src/components/Modals/OpenQuestion.vue')['default']
    ProfileModal: typeof import('./src/components/ProfileModal.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    Question: typeof import('./src/components/Modals/Question.vue')['default']
    Quiz: typeof import('./src/components/Quiz.vue')['default']
    QuizBlock: typeof import('./src/components/QuizBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarLink: typeof import('./src/components/SidebarLink.vue')['default']
    Tiptap: typeof import('./src/components/Tiptap.vue')['default']
    UploadPlugin: typeof import('./src/components/UploadPlugin.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
    UserDropdown: typeof import('./src/components/UserDropdown.vue')['default']
    VideoBlock: typeof import('./src/components/VideoBlock.vue')['default']
  }
}
