# Copyright (c) 2026, Klisia / SeminaryERP and contributors
# For license information, please see license.txt
"""Security response headers (p008 F14, p005a A02-9).

Before this the app shipped **no security headers at all**: no CSP, no
`X-Frame-Options`, no `nosniff`, no `Referrer-Policy`. What protected the site
was the bench-generated `config/nginx.conf` -- outside this repo, regenerated by
`bench setup nginx`, and absent under `bench serve`, in a container, or behind
any other proxy. Even there, two gaps: `add_header` does not inherit into a
`location` that declares its own, so the `/assets` and `/files/*.html|svg` blocks
drop the whole server-level set; and `add_header` skips non-2xx/3xx, so every
error page is bare. Neither layer had a CSP.

## Why CSP belongs in Phase 2 rather than Phase 3

It is the only control that caps all ninety `v-html` sinks and the A05-1
pre-parse bypass **at once**, including the paths F1-F6 cannot reach --
server-rendered website pages, and any sink a future commit adds before the F13
contract test catches it. It is the compensating control for everything this
phase does not close.

## Report-only first, and why that is not hedging

An enforcing CSP that is wrong takes the site down; the failure mode is a blank
page, not a warning. `CSP_ENFORCE` stays False until violations have been
collected across Desk and the SPA. Flip it with `seminary_csp_enforce` in
site_config once the reports are clean -- no code change, so the rollback is the
same one-line edit.
"""

from __future__ import annotations

import frappe

#: Origins that actually execute script in an authenticated session. Keep this
#: list honest: every entry is a party that can run code as the user.
#:
#: **Empty, and that is the finding.** F14 named `kit.fontawesome.com` because
#: p005a A03-1 said the Desk loaded a Font Awesome kit. It never did:
#: `public/js/seminary.bundle.js` was 74 bytes of *HTML attribute fragment*
#: (`src="..." , crossorigin="anonymous"`) pasted into a `.js` file, it was not
#: in `app_include_js`, and a deployed page on the canary carried zero
#: references to fontawesome. Nothing loaded it, so the origin is gone with the
#: file (p010 H12).
SCRIPT_ORIGINS = ()

#: cdn.jsdelivr.net is *not* here: A03-3 was real -- the highlight.js theme is
#: in the deployed `index-*.js` and loads on every lesson view -- and p010 H12
#: vendors it from the `highlight.js` package we already depend on, rather than
#: keeping a CDN in the policy.
STYLE_ORIGINS = ("https://fonts.googleapis.com",)
FONT_ORIGINS = ("https://fonts.gstatic.com",)

#: Frappe's Desk and the SPA both inline scripts and styles (boot data, Vue's
#: injected styles), so 'unsafe-inline' cannot come out without vendoring both.
#: Recorded rather than quietly accepted: it is the reason this CSP mitigates
#: rather than eliminates the `v-html` class, and why F1-F6 still had to be done.
_SELF_INLINE = "'self' 'unsafe-inline'"


def _directives() -> list[str]:
    script = " ".join(("'self'", "'unsafe-inline'", "'unsafe-eval'", *SCRIPT_ORIGINS))
    style = " ".join((_SELF_INLINE, *STYLE_ORIGINS))
    font = " ".join(("'self'", "data:", *FONT_ORIGINS))
    return [
        "default-src 'self'",
        f"script-src {script}",
        f"style-src {style}",
        f"font-src {font}",
        # `data:` for editor-pasted images; `blob:` for locally recorded media.
        "img-src 'self' data: blob: https:",
        "media-src 'self' data: blob: https:",
        # Lessons legitimately frame YouTube, Genially and the like; the iframe
        # tool checks the URL before it is ever stored (p008 F4).
        "frame-src 'self' https:",
        "connect-src 'self' https: wss: ws:",
        # 'self', not 'none': the app frames its own pages. `embed_renderer`'s
        # `type == "pdf"` branch exists precisely to iframe a site-hosted PDF
        # (p008 F5), and 'none' forbids *all* framing, same-origin included --
        # it broke PDF rendering in the owner's browser pass. Cross-origin
        # framing is still refused, which is the clickjacking control.
        "frame-ancestors 'self'",
        "object-src 'none'",
        "base-uri 'self'",
        "form-action 'self'",
    ]


def csp_enforced() -> bool:
    return bool(frappe.conf.get("seminary_csp_enforce"))


def policy() -> str:
    return "; ".join(_directives())


def apply_security_headers(response=None, request=None, **kwargs):
    """`after_request`. Never raises: a header must not cost a response.

    Frappe calls this for every request that reached the framework, including
    error responses -- which is exactly where the nginx layer gives up.
    """
    if response is None:
        return
    try:
        from seminary.scorm.delivery import is_delivery_request

        if is_delivery_request():
            # The SCORM delivery origin carries its own complete policy
            # (p009 §2.6) and it is deliberately a different one: a CSP loose
            # enough to run real courseware, and `frame-ancestors` naming the
            # APP origin rather than 'self'.
            #
            # The header that actually breaks is `X-Frame-Options: SAMEORIGIN`
            # below. Set on a delivery response it forbids the app origin from
            # framing the package -- so the player renders nothing, in every
            # browser, with no error the app can see. Found on the first live
            # pass; nothing short of a real cross-origin request shows it.
            return
        headers = response.headers
        header = (
            "Content-Security-Policy"
            if csp_enforced()
            else "Content-Security-Policy-Report-Only"
        )
        headers.setdefault(header, policy())
        headers.setdefault("X-Content-Type-Options", "nosniff")
        # Must track `frame-ancestors` above: DENY blocks same-origin framing
        # too, and browsers that honour both apply the stricter one, so a DENY
        # here would silently undo the 'self' in the CSP.
        headers.setdefault("X-Frame-Options", "SAMEORIGIN")
        headers.setdefault("Referrer-Policy", "strict-origin-when-cross-origin")
        headers.setdefault("Permissions-Policy", "geolocation=(), payment=(), usb=()")
    except Exception:
        frappe.logger().error("could not set security headers", exc_info=True)
